### ISSUE TITLE
Griff's suggested name changes

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/withdrawcontract#3]
In general, i think we should call the sends the owner makes to the contract "Deposits" the transfers that happen of all the tokens and eth to the user a "withdraw" and the individual transfers that make up a withdraw "Payments"

So this means we need to do a big ctrl-F on this and replace Payment with Deposit for everything EXCEPT doPayment, keep doPayment as doPayment :-D 

getPendingReward = getPendingPayment

nextRefundToPay = nextDepositToPayout

distToken = rewardToken

hasFundsAvailable() = canWithdraw()

isPaymentSkiped = isDepositSkipped

tokenHolder = holder

**Comment by jbaylina** [comment]
Done!
